displayName=Burthorpe Sell Calculator
author=G1M Labor
description=Calculate your shop sell value for Martin in Burthorpe, includes useful menuswaps and highlights for selling.
tags=
version=1.01
plugins=com.burthorpesellcalc.burthorpecalcplugin
build=standard
