displayName=Burthorpe Sell Calculator
author=G1M Labor
description=Calculates set items money gained for selling them at shops for set quantities per world per item.
tags=
version=1.0
plugins=com.burthorpesellcalc.burthorpecalcplugin
build=standard
